### ISSUE TITLE
Please add an Open source License

### ISSUE THREAD

**Issue by bensaine** [smaameri/multi-doc-chatbot#4]
It would be useful if you could provide an open source license to this repository to define the rights you reserve and the ones you want to give to the public. At the moment, I don't know how I can use this code as it's assume that you reserve all rights to this code, thus not open source.

**Comment by smaameri** [comment]
@bensaine  Thanks for bringing this up. Have added an MIT License to the repo

**Comment by bensaine** [comment]
Thanks!
