### ISSUE TITLE
Paid plan?

### ISSUE THREAD

**Issue by venky3692** [smaameri/multi-doc-chatbot#5]
It shows me this - openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
Will I be needing a paid plan? Please let me know

**Comment by yepher** [comment]
This needs to you your OpenAI account Api key:

https://github.com/smaameri/multi-doc-chatbot/blob/master/.env.example#L1

You can get your OpenAI API key here: https://platform.openai.com/account/api-keys

**Comment by estkae** [comment]
This Error ist still on:
Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
Maybe a wait section Parameter but where?

**Comment by estkae** [comment]
Try it with this:
vectordb = Chroma.from_documents(documents, embedding=embeddings) #, persist_directory="./data")
#vectordb.persist()

and it works!

**Comment by JayarajDeveloper** [comment]
how to restrict answer that question which is not relevant to docs . please advise
